spring.application.name=helma-api-gateway
server.port=8080

server.forward-headers-strategy=framework

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200,http://localhost}
app.jwt.secret=${APP_JWT_SECRET}